---

- name: Initial configuration for {{ application_name }} SSL
  hosts: production
  become: yes
  become_user: root
  remote_user: ubuntu
  vars:
    - update_apt_cache: yes
  vars_files:
    - env_vars/production.yml

  roles:
    - certbot